### ISSUE TITLE
Segmentation Fault when Running Query without `-t` Option

### ISSUE THREAD

**Issue by lxhq** [magic62442/subgraph-counting#1]
**Description:**

Thank you for sharing this great work. I’ve been able to run several queries successfully, but I encountered a runtime error when running specific queries without the `-t` option.

**Issue Details:**

For instance, I encountered a segmentation fault when executing the query `5voc/68.txt` without using the `-t` option.

**Command Executed:**

```bash
./build/executable/scope.out -q ./exp/pattern_graph/5voc/68.txt -d ./exp/data_graph/web-spam.txt -r ./result/5voc/web-spam/68.txt
```

**Output:**
```yaml
query graph path: ./exp/pattern_graph/5voc/68.txt
data graph path: ./exp/data_graph/web-spam.txt
result path: ./result/5voc/web-spam/68.txt
using batch query: 0
sharing nodes computation: 0
using triangle: 0
set intersection type: 0
finished building edge ID mappings. time: 0.00484188s
Segmentation fault (core dumped)
```
